version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc

dockers:
  - image_templates:
      - "yardenshoham/{{.ProjectName}}"
      - "yardenshoham/{{.ProjectName}}:v{{ .Version }}"
      - "yardenshoham/{{.ProjectName}}:{{ .Version }}"
      - "yardenshoham/{{.ProjectName}}:{{ .ShortCommit }}"
    use: buildx
    build_flag_templates:
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/yardenshoham/skim/refs/heads/main/README.md"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Yarden Shoham","email":"skim@yardenshoham.com"}]'
      - "--label=io.artifacthub.package.license=Apache-2.0"
      - "--label=org.opencontainers.image.description=Scan Kubernetes Images from Manifests"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
