package images

var imagelessGVKs = map[string]struct{}{
	"v1.Namespace":                                                   {},
	"storage.k8s.io/v1.StorageClass":                                 {},
	"apiextensions.k8s.io/v1.CustomResourceDefinition":               {},
	"v1.ServiceAccount":                                              {},
	"v1.Service":                                                     {},
	"networking.k8s.io/v1.Ingress":                                   {},
	"networking.k8s.io/v1.IngressClass":                              {},
	"autoscaling/v1.HorizontalPodAutoscaler":                         {},
	"v1.ConfigMap":                                                   {},
	"monitoring.coreos.com/v1.PodMonitor":                            {},
	"networking.k8s.io/v1.NetworkPolicy":                             {},
	"v1.Secret":                                                      {},
	"rbac.authorization.k8s.io/v1.ClusterRole":                       {},
	"rbac.authorization.k8s.io/v1.RoleBinding":                       {},
	"monitoring.coreos.com/v1.PrometheusRule":                        {},
	"policy/v1.PodDisruptionBudget":                                  {},
	"monitoring.coreos.com/v1.ServiceMonitor":                        {},
	"autoscaling/v2.HorizontalPodAutoscaler":                         {},
	"v1.PersistentVolumeClaim":                                       {},
	"rbac.authorization.k8s.io/v1.ClusterRoleBinding":                {},
	"rbac.authorization.k8s.io/v1.Role":                              {},
	"kafka.strimzi.io/v1beta2.KafkaNodePool":                         {},
	"tekton.dev/v1beta1.TaskRun":                                     {},
	"triggers.tekton.dev/v1beta1.TriggerBinding":                     {},
	"triggers.tekton.dev/v1beta1.ClusterTriggerBinding":              {},
	"monitoring.coreos.com/v1alpha1.AlertmanagerConfig":              {},
	"triggers.tekton.dev/v1alpha1.ClusterInterceptor":                {},
	"admissionregistration.k8s.io/v1.MutatingWebhookConfiguration":   {},
	"admissionregistration.k8s.io/v1.ValidatingWebhookConfiguration": {},
	"kyverno.io/v1.ClusterPolicy":                                    {},
	"kyverno.io/v1.Policy":                                           {},
	"cert-manager.io/v1.Certificate":                                 {},
	"cert-manager.io/v1.ClusterIssuer":                               {},
	"cert-manager.io/v1.Issuer":                                      {},
}
